### ISSUE TITLE
Add basic api.ai integration

### ISSUE THREAD

**Issue by Laged** [Kanttiinit/audio#2]
It should pass the audio file to API.ai and get a classification to know which restaurant the user requests

**Comment by Laged** [comment]
https://github.com/Kanttiinit/bot/blob/master/bot/commandDescriptions.txt

It should classify the voice request into a valid restaurant from the bot ^

**Comment by quody** [comment]
Instead of API.AI use Google Cloud Speech API to better support Finnish pronunciation of restaurant names.
