### ISSUE TITLE
Add text resetting from a button

### ISSUE THREAD

**Issue by Laged** [Kanttiinit/audio#4]
Remove written text by clicking a button

**Comment by Acollie** [comment]
Sure I will take this, can you be more specific  on 'a button'

**Comment by anant-dev** [comment]
hi @Laged I have made a button that clears the text field. Please find the pr(#7) adressing this issue.
![a](https://cloud.githubusercontent.com/assets/13196029/19854288/3af245bc-9f94-11e6-85f1-5176975df9f9.png)
